language: node_js
node_js:
- 8.9.1
deploy:
  provider: npm
  email: toshok@toshokelectric.com
  on:
    tags: true
    repo: honeycombio/honeycomb-nodejs-magic
  api_key:
    secure: WuU/Br10qu9Yq8SEynqXuYupuguLLSQRixzmJKpbZBlZpfXuov3n6P0Fn5CX8uePEdBk9UkuErbP8bUstk/Rj0iU0meCFsJ8VVRt2x+g5b0+XVejkBr3mvSWLGrlUTmrg4KgbDV0gfKdhOEzvbgutqT2IsUSfvmYZipfvvI99V0X/FdMmw4WYetUW2Ibv3/gi2Yp2LFgtFZBGtKanfSp/Kfm6qUQWcCVZZI0B+qgQri6F++VqRe9JZhV0DxV8yrTrJrJ/hs9/y7vwEAsvQ0ckT6Nmxyu6pVYLvLMBxQGqeemsEmPyG4tjd5UC1xuS7SyhfgGuBba9bUIYlAUit/45Hg5iZNfNbURpftRqZvGcnKu04XKkfUpA70XMBIWZAVhK7pa+yMqqu1GbEEpOIUif8f4rX4xFWH5+yBuEAKvRrF/B/ppm0ooryk0sL7TjjBGSGS6l+quzSYAj3AkRyzcB+VO5KzXUGOqqELeaXL97u6VlQMEErVNU/tlbdckcBeVwyZUpuw7qPWo0A9iQQloFZa1c50aUaHVBAMRMZpmvd2FGsr2avvpH5wGV4O7+38kGQz9TGxy/i+NfvLK1Wqv3yZTM3oapfxqLedM2aOukGDDL/GatoHtC8QMR288GZPXKOOddlM2aPCd3yIQ6CskhyfVLLL8topwcTnv6YBPst0=
notifications:
  slack:
    rooms:
      - secure: "oGESz+fJtd0cSSRRvMAEpDARhuv3ZrivAZ9dmpKKA/ZuVxC3Nes8Ou7lC3HLhinL7IFr6BOPkw4013jjqO8Gcl5ttJUN77MlaeQNgn8ca+infMgeXF/ZuHVzsorv+eOZnQ/o07Mq6er3PlJOKyT1RiIonHuOtJZpXXdFHsi5T4aiUWcWr35wXNCa0r/GVBJF4Ww1b20EsVQv/8T3x2V3sJ6c+rCuBCDVpDlK2FpygpCmvRxJrM6S8Op5KggH6+0o/Us1FtKqJT8O/mX9ITgNJZ1wmzrhsO8CMldF2D4WRkkvP4kWtb+QF2Y5nJA8v6ukzRaxUhi4XqNazjmEsxOBojR+RiogB0DaMlkonIC5bnuM0xFPzcOnd+/CeC5z//gCY+UhaFLpb1GwPrXfT3RUPHrK3weTL5TvDMgt3lD6pLUmP2wzBjcEawPM9xYdla4GaEIrHaPG9fQTBPJvTG/U8N9hKSKfHGVI9MDOlF6Nl/8d5uPObkUMq417PFGW6s0KhRGGPWAPLFtJtA7ZW/ILfsZMDMDM7T5F/kmiwN3F0YoELV7HgAybf8Gcj0JF7wzf/2wcRhHrUnKqpoAk4h1XQfyoI8rfWQnkoUsz75HBINDLsVMRZltl43iwHvFl0kEB2Cm/tt0yqRtsq1mUK2As1Obj2RKM/GQ1rwh00Hc3K78="
    on_failure: always
    on_success: always
