language: node_js
node_js:
- 8.9.1
deploy:
  provider: npm
  email: toshok@toshokelectric.com
  on:
    tags: true
    repo: honeycombio/honeycomb-nodejs-magic
  api_key:
    secure: WuU/Br10qu9Yq8SEynqXuYupuguLLSQRixzmJKpbZBlZpfXuov3n6P0Fn5CX8uePEdBk9UkuErbP8bUstk/Rj0iU0meCFsJ8VVRt2x+g5b0+XVejkBr3mvSWLGrlUTmrg4KgbDV0gfKdhOEzvbgutqT2IsUSfvmYZipfvvI99V0X/FdMmw4WYetUW2Ibv3/gi2Yp2LFgtFZBGtKanfSp/Kfm6qUQWcCVZZI0B+qgQri6F++VqRe9JZhV0DxV8yrTrJrJ/hs9/y7vwEAsvQ0ckT6Nmxyu6pVYLvLMBxQGqeemsEmPyG4tjd5UC1xuS7SyhfgGuBba9bUIYlAUit/45Hg5iZNfNbURpftRqZvGcnKu04XKkfUpA70XMBIWZAVhK7pa+yMqqu1GbEEpOIUif8f4rX4xFWH5+yBuEAKvRrF/B/ppm0ooryk0sL7TjjBGSGS6l+quzSYAj3AkRyzcB+VO5KzXUGOqqELeaXL97u6VlQMEErVNU/tlbdckcBeVwyZUpuw7qPWo0A9iQQloFZa1c50aUaHVBAMRMZpmvd2FGsr2avvpH5wGV4O7+38kGQz9TGxy/i+NfvLK1Wqv3yZTM3oapfxqLedM2aOukGDDL/GatoHtC8QMR288GZPXKOOddlM2aPCd3yIQ6CskhyfVLLL8topwcTnv6YBPst0=
notifications:
  slack:
    rooms:
      - secure: WFMDwPSzINDYByhSdiAot2LBNEsgMsHbTufmU9qllEHt/rq/VeS9GglLXCym54tzJPD5ua36MBxwaVxobRKjBKTTo84hKfr10Ut1HV5K3b7woeqQu5hs/F0F4Ecq/AIZwrGvbslDb+irpn0oSqUcaG36rugW6ZtwepUdxE2fV3T84GaUUqIz+3w/YGJTfD9P6SWOasVBmNASclFzTUIYaReSk7ebmjWcZm2PTUmw+cAwxGd2YL+TFO+Rpwnc688E3imQfooXYq1HCwo7TwjN1uudDBtsIyzWGwUhCJgkNMHSzZb3nZfpxxGgJSMSkz7BUBzp5/CXDknfw+FWK+mNukZ2PaaKYQh6Ajzw9AIRzeK1RlqvDWPRdL51exFZCcfonUPJx0jkbMqmU/nNGENxss4oA7RuTJkOFkkwFuQE9mC30ob5uQrDSQ3rmPaH49BP0KR+q8HTmfbTmu6qW3mp6GvTdDbR5cjxtkimx3ZJDVs9fU1IaGx1QYlK8MJApK7AA6HLnHLgcWNpgta7IXRSmlAo9lbCcnpdVl97Gi9Sx/QOdBu5Bp9BmXQIsQLVlGJgCRj2f7vnDj0I3D3PRTDycQYvGLu8/F+8orYXbkenzfq0OsJqVu0KoaE2dk2SidEaz3V79IQvicG5ATwogyEHqx+fs5F17PBknnoOLu8ah68=
    on_failure: always
    on_success: always
